In [1]:
    theta_x1 = np.cos(df[:, 2])
    theta_x1 = theta_x1.reshape(-1, 1)
    theta_y1 = np.sin(df[:, 2])
    theta_y1 = theta_y1.reshape(-1, 1)
    theta_x2 = np.cos(df[:, 5])
    theta_x2 = theta_x2.reshape(-1, 1)
    theta_y2 = np.sin(df[:, 5])
    theta_y2 = theta_y2.reshape(-1, 1)

    columns_to_delete = [2, 5] 
    df = np.delete(df, columns_to_delete, axis=1)

    df = np.concatenate((df, theta_x1), axis=1)
    df = np.concatenate((df, theta_y1), axis=1)
    df = np.concatenate((df, theta_x2), axis=1)
    df = np.concatenate((df, theta_y2), axis=1)

    X = df[:, np.arange(df.shape[1]) != 5]
    y = df[:, 5]

NameError: name 'np' is not defined

In [1]:
import numpy as np
import pandas as pd
df = pd.read_csv('testpara.csv')
df

InnerRadius    Length  OpeningAngle  InnerRadius2   Length2  \
0         3.90874   61.5669      0.052689      2.016570  139.4330   
1         1.99530   72.1412      0.027506      6.259420  134.1270   
2         2.09463  132.2190      0.014867      0.134743  134.8410   
3         3.30559  100.8360      0.037702      0.886785   60.7252   
4         4.60422  114.9840      0.023466      2.387690  105.4090   
...           ...       ...           ...           ...       ...   
1595      4.28358   60.7801      0.051802      0.864755  125.4670   
1596      0.26626  106.3190      0.057043      0.189079  110.6910   
1597      2.24934  101.7440      0.028651      2.080260  110.8800   
1598      2.12298   84.1852      0.002679      2.080710  111.5570   
1599      2.51934  107.2380      0.007103      0.702851   41.7374   

      OpeningAngle2  Generation  Fitness  
0          0.012688           0  4.07216  
1          0.004807           0  4.18268  
2          0.016945           0  3.72230  
3          0.048279           0  4.45808  
4          0.019864           0  3.94431  
...             ...         ...      ...  
1595       0.011695          31  4.05299  
1596       0.038525          31  4.20008  
1597       0.043964          31  4.01570  
1598       0.043115          31  4.15416  
1599       0.160602          31  4.63660  

[1600 rows x 8 columns]

In [2]:
df = df.to_numpy()
df

array([[3.90874e+00, 6.15669e+01, 5.26890e-02, ..., 1.26880e-02,
        0.00000e+00, 4.07216e+00],
       [1.99530e+00, 7.21412e+01, 2.75060e-02, ..., 4.80700e-03,
        0.00000e+00, 4.18268e+00],
       [2.09463e+00, 1.32219e+02, 1.48670e-02, ..., 1.69450e-02,
        0.00000e+00, 3.72230e+00],
       ...,
       [2.24934e+00, 1.01744e+02, 2.86510e-02, ..., 4.39640e-02,
        3.10000e+01, 4.01570e+00],
       [2.12298e+00, 8.41852e+01, 2.67900e-03, ..., 4.31150e-02,
        3.10000e+01, 4.15416e+00],
       [2.51934e+00, 1.07238e+02, 7.10300e-03, ..., 1.60602e-01,
        3.10000e+01, 4.63660e+00]])

In [3]:
df[:, 2]

array([0.052689, 0.027506, 0.014867, ..., 0.028651, 0.002679, 0.007103])

In [6]:
df[:,5]

array([0.012688, 0.004807, 0.016945, ..., 0.043964, 0.043115, 0.160602])

In [8]:
theta_x1 = np.cos(df[:, 2])
theta_x1 = theta_x1.reshape(-1, 1)
theta_y1 = np.sin(df[:, 2])
theta_y1 = theta_y1.reshape(-1, 1)
theta_x2 = np.cos(df[:, 5])
theta_x2 = theta_x2.reshape(-1, 1)
theta_y2 = np.sin(df[:, 5])
theta_y2 = theta_y2.reshape(-1, 1)

In [9]:
theta_x1

array([[0.99861226],
       [0.99962173],
       [0.99988949],
       ...,
       [0.99958959],
       [0.99999641],
       [0.99997477]])

In [10]:
# delete columns(OpeningAngle, OpeningAngle2)
columns_to_delete = [2, 5, 6] 
df = np.delete(df, columns_to_delete, axis=1)

In [11]:
df

array([[3.90874e+00, 6.15669e+01, 2.01657e+00, 1.39433e+02, 4.07216e+00],
       [1.99530e+00, 7.21412e+01, 6.25942e+00, 1.34127e+02, 4.18268e+00],
       [2.09463e+00, 1.32219e+02, 1.34743e-01, 1.34841e+02, 3.72230e+00],
       ...,
       [2.24934e+00, 1.01744e+02, 2.08026e+00, 1.10880e+02, 4.01570e+00],
       [2.12298e+00, 8.41852e+01, 2.08071e+00, 1.11557e+02, 4.15416e+00],
       [2.51934e+00, 1.07238e+02, 7.02851e-01, 4.17374e+01, 4.63660e+00]])

In [12]:
df[0,4]

4.07216

In [13]:
df = np.concatenate((df, theta_x1), axis=1)
df = np.concatenate((df, theta_y1), axis=1)
df = np.concatenate((df, theta_x2), axis=1)
df = np.concatenate((df, theta_y2), axis=1)

In [14]:
df

array([[3.90874000e+00, 6.15669000e+01, 2.01657000e+00, ...,
        5.26646248e-02, 9.99919508e-01, 1.26876596e-02],
       [1.99530000e+00, 7.21412000e+01, 6.25942000e+00, ...,
        2.75025317e-02, 9.99988446e-01, 4.80698149e-03],
       [2.09463000e+00, 1.32219000e+02, 1.34743000e-01, ...,
        1.48664523e-02, 9.99856437e-01, 1.69441891e-02],
       ...,
       [2.24934000e+00, 1.01744000e+02, 2.08026000e+00, ...,
        2.86470803e-02, 9.99033739e-01, 4.39498389e-02],
       [2.12298000e+00, 8.41852000e+01, 2.08071000e+00, ...,
        2.67899680e-03, 9.99070692e-01, 4.31016435e-02],
       [2.51934000e+00, 1.07238000e+02, 7.02851000e-01, ...,
        7.10294027e-03, 9.87131195e-01, 1.59912489e-01]])

In [38]:
np.set_printoptions(threshold=np.inf)
print(df) 

[[3.90874000e+00 6.15669000e+01 2.01657000e+00 1.39433000e+02
  4.07216000e+00 9.98612256e-01 5.26646248e-02 9.99919508e-01
  1.26876596e-02]
 [1.99530000e+00 7.21412000e+01 6.25942000e+00 1.34127000e+02
  4.18268000e+00 9.99621734e-01 2.75025317e-02 9.99988446e-01
  4.80698149e-03]
 [2.09463000e+00 1.32219000e+02 1.34743000e-01 1.34841000e+02
  3.72230000e+00 9.99889488e-01 1.48664523e-02 9.99856437e-01
  1.69441891e-02]
 [3.30559000e+00 1.00836000e+02 8.86785000e-01 6.07252000e+01
  4.45808000e+00 9.99289364e-01 3.76930688e-02 9.98834795e-01
  4.82602469e-02]
 [4.60422000e+00 1.14984000e+02 2.38769000e+00 1.05409000e+02
  3.94431000e+00 9.99724686e-01 2.34638465e-02 9.99802717e-01
  1.98626937e-02]
 [4.24654000e+00 6.04922000e+01 1.19594000e+00 4.01511000e+01
  4.59291000e+00 9.99967147e-01 8.10591123e-03 9.90378584e-01
  1.38384467e-01]
 [3.60877000e+00 3.84541000e+01 3.10000000e+00 1.29194000e+02
  4.14528000e+00 9.96025297e-01 8.90708021e-02 9.99528546e-01
  3.07031740e-02]
 [3.38

In [15]:
df.shape

(1600, 9)

In [16]:
y = df[:, 4]
y

array([4.07216, 4.18268, 3.7223 , ..., 4.0157 , 4.15416, 4.6366 ])

In [17]:
X = df[:, np.arange(df.shape[1]) != 4]
X

array([[3.90874000e+00, 6.15669000e+01, 2.01657000e+00, ...,
        5.26646248e-02, 9.99919508e-01, 1.26876596e-02],
       [1.99530000e+00, 7.21412000e+01, 6.25942000e+00, ...,
        2.75025317e-02, 9.99988446e-01, 4.80698149e-03],
       [2.09463000e+00, 1.32219000e+02, 1.34743000e-01, ...,
        1.48664523e-02, 9.99856437e-01, 1.69441891e-02],
       ...,
       [2.24934000e+00, 1.01744000e+02, 2.08026000e+00, ...,
        2.86470803e-02, 9.99033739e-01, 4.39498389e-02],
       [2.12298000e+00, 8.41852000e+01, 2.08071000e+00, ...,
        2.67899680e-03, 9.99070692e-01, 4.31016435e-02],
       [2.51934000e+00, 1.07238000e+02, 7.02851000e-01, ...,
        7.10294027e-03, 9.87131195e-01, 1.59912489e-01]])

In [40]:
np.set_printoptions(threshold=np.inf)
print(X) 


[[3.90874000e+00 6.15669000e+01 2.01657000e+00 1.39433000e+02
  9.98612256e-01 5.26646248e-02 9.99919508e-01 1.26876596e-02]
 [1.99530000e+00 7.21412000e+01 6.25942000e+00 1.34127000e+02
  9.99621734e-01 2.75025317e-02 9.99988446e-01 4.80698149e-03]
 [2.09463000e+00 1.32219000e+02 1.34743000e-01 1.34841000e+02
  9.99889488e-01 1.48664523e-02 9.99856437e-01 1.69441891e-02]
 [3.30559000e+00 1.00836000e+02 8.86785000e-01 6.07252000e+01
  9.99289364e-01 3.76930688e-02 9.98834795e-01 4.82602469e-02]
 [4.60422000e+00 1.14984000e+02 2.38769000e+00 1.05409000e+02
  9.99724686e-01 2.34638465e-02 9.99802717e-01 1.98626937e-02]
 [4.24654000e+00 6.04922000e+01 1.19594000e+00 4.01511000e+01
  9.99967147e-01 8.10591123e-03 9.90378584e-01 1.38384467e-01]
 [3.60877000e+00 3.84541000e+01 3.10000000e+00 1.29194000e+02
  9.96025297e-01 8.90708021e-02 9.99528546e-01 3.07031740e-02]
 [3.38546000e+00 9.71822000e+01 3.41558000e+00 4.56548000e+01
  9.99612492e-01 2.78364038e-02 9.99599157e-01 2.83112166e-02]


In [18]:
X.shape

(1600, 8)

In [19]:
np.set_printoptions(threshold=np.inf)
print(X[:1])

[[3.90874000e+00 6.15669000e+01 2.01657000e+00 1.39433000e+02
  9.98612256e-01 5.26646248e-02 9.99919508e-01 1.26876596e-02]]


In [20]:
import math
import torch


def positionalencoding1d(d_model, length):
    """
    :param d_model: dimension of the model
    :param length: length of positions
    :return: length*d_model position matrix
    """
    if d_model % 2 != 0:
        raise ValueError("Cannot use sin/cos positional encoding with "
                         "odd dim (got dim={:d})".format(d_model))
    pe = torch.zeros(length, d_model)
    position = torch.arange(0, length).unsqueeze(1)
    div_term = torch.exp((torch.arange(0, d_model, 2, dtype=torch.float) *
                         -(math.log(10000.0) / d_model)))
    pe[:, 0::2] = torch.sin(position.float() * div_term)
    pe[:, 1::2] = torch.cos(position.float() * div_term)

    return pe

In [29]:
length = 1600  # 最大序列长度
d_model = 8  # 编码维度
pos_encoding = positionalencoding1d(d_model, length)
print(pos_encoding)

tensor([[ 0.0000e+00,  1.0000e+00,  0.0000e+00,  ...,  1.0000e+00,
          0.0000e+00,  1.0000e+00],
        [ 8.4147e-01,  5.4030e-01,  9.9833e-02,  ...,  9.9995e-01,
          1.0000e-03,  1.0000e+00],
        [ 9.0930e-01, -4.1615e-01,  1.9867e-01,  ...,  9.9980e-01,
          2.0000e-03,  1.0000e+00],
        ...,
        [ 8.7765e-01,  4.7931e-01,  4.9795e-01,  ..., -9.6586e-01,
          9.9966e-01, -2.6201e-02],
        [ 8.7752e-01, -4.7954e-01,  4.0889e-01,  ..., -9.6323e-01,
          9.9963e-01, -2.7200e-02],
        [ 7.0602e-02, -9.9750e-01,  3.1574e-01,  ..., -9.6049e-01,
          9.9960e-01, -2.8200e-02]])


In [30]:
X_tensor = torch.tensor(X, dtype=torch.float32)

In [31]:
X.shape

(1600, 8)

In [32]:
X_tensor+pos_encoding

tensor([[ 3.9087e+00,  6.2567e+01,  2.0166e+00,  ...,  1.0527e+00,
          9.9992e-01,  1.0127e+00],
        [ 2.8368e+00,  7.2682e+01,  6.3593e+00,  ...,  1.0275e+00,
          1.0010e+00,  1.0048e+00],
        [ 3.0039e+00,  1.3180e+02,  3.3341e-01,  ...,  1.0147e+00,
          1.0019e+00,  1.0169e+00],
        ...,
        [ 3.1270e+00,  1.0222e+02,  2.5782e+00,  ..., -9.3722e-01,
          1.9987e+00,  1.7749e-02],
        [ 3.0005e+00,  8.3706e+01,  2.4896e+00,  ..., -9.6055e-01,
          1.9987e+00,  1.5901e-02],
        [ 2.5899e+00,  1.0624e+02,  1.0186e+00,  ..., -9.5339e-01,
          1.9867e+00,  1.3171e-01]])

In [36]:
1600*0.85

1360.0

In [35]:
pos_encoding_train = pos_encoding[1120, :]
pos_encoding_val = pos_encoding[1121:1360, :]
pos_encoding_test = pos_encoding[1361:, :]
