In [1]:
    theta_x1 = np.cos(df[:, 2])
    theta_x1 = theta_x1.reshape(-1, 1)
    theta_y1 = np.sin(df[:, 2])
    theta_y1 = theta_y1.reshape(-1, 1)
    theta_x2 = np.cos(df[:, 5])
    theta_x2 = theta_x2.reshape(-1, 1)
    theta_y2 = np.sin(df[:, 5])
    theta_y2 = theta_y2.reshape(-1, 1)

    columns_to_delete = [2, 5] 
    df = np.delete(df, columns_to_delete, axis=1)

    df = np.concatenate((df, theta_x1), axis=1)
    df = np.concatenate((df, theta_y1), axis=1)
    df = np.concatenate((df, theta_x2), axis=1)
    df = np.concatenate((df, theta_y2), axis=1)

    X = df[:, np.arange(df.shape[1]) != 5]
    y = df[:, 5]

NameError: name 'np' is not defined

In [66]:
import numpy as np
import pandas as pd
df = pd.read_csv('testpara.csv')
df

InnerRadius    Length  OpeningAngle  InnerRadius2   Length2  \
0         3.90874   61.5669      0.052689      2.016570  139.4330   
1         1.99530   72.1412      0.027506      6.259420  134.1270   
2         2.09463  132.2190      0.014867      0.134743  134.8410   
3         3.30559  100.8360      0.037702      0.886785   60.7252   
4         4.60422  114.9840      0.023466      2.387690  105.4090   
...           ...       ...           ...           ...       ...   
1595      4.28358   60.7801      0.051802      0.864755  125.4670   
1596      0.26626  106.3190      0.057043      0.189079  110.6910   
1597      2.24934  101.7440      0.028651      2.080260  110.8800   
1598      2.12298   84.1852      0.002679      2.080710  111.5570   
1599      2.51934  107.2380      0.007103      0.702851   41.7374   

      OpeningAngle2  Generation  Fitness  
0          0.012688           0  4.07216  
1          0.004807           0  4.18268  
2          0.016945           0  3.72230  
3          0.048279           0  4.45808  
4          0.019864           0  3.94431  
...             ...         ...      ...  
1595       0.011695          31  4.05299  
1596       0.038525          31  4.20008  
1597       0.043964          31  4.01570  
1598       0.043115          31  4.15416  
1599       0.160602          31  4.63660  

[1600 rows x 8 columns]

In [67]:
df = df.to_numpy()
df

array([[3.90874e+00, 6.15669e+01, 5.26890e-02, ..., 1.26880e-02,
        0.00000e+00, 4.07216e+00],
       [1.99530e+00, 7.21412e+01, 2.75060e-02, ..., 4.80700e-03,
        0.00000e+00, 4.18268e+00],
       [2.09463e+00, 1.32219e+02, 1.48670e-02, ..., 1.69450e-02,
        0.00000e+00, 3.72230e+00],
       ...,
       [2.24934e+00, 1.01744e+02, 2.86510e-02, ..., 4.39640e-02,
        3.10000e+01, 4.01570e+00],
       [2.12298e+00, 8.41852e+01, 2.67900e-03, ..., 4.31150e-02,
        3.10000e+01, 4.15416e+00],
       [2.51934e+00, 1.07238e+02, 7.10300e-03, ..., 1.60602e-01,
        3.10000e+01, 4.63660e+00]])

In [57]:
df[:, 6]

array([ 0.,  0.,  0., ..., 31., 31., 31.])

In [68]:
df = np.delete(df, 6, axis=1)

In [69]:
X = df[:, np.arange(df.shape[1]) != 6]
y = df[:, 6]

In [60]:
0-InnerRadius	
1-Length	
2-OpeningAngle	
3-InnerRadius2	
4-Length2	
5-OpeningAngle2	

y-Fitness

NameError: name 'InnerRadius' is not defined

In [70]:
X_length2 = X[:, 4] 
X_length2

array([139.433 , 134.127 , 134.841 , ..., 110.88  , 111.557 ,  41.7374])

In [71]:

print("Original Array:")
print(X)

X = np.delete(X, 4, axis=1)
print("\nArray after removing the fourth column:")
print(X)



Original Array:
[[3.90874e+00 6.15669e+01 5.26890e-02 2.01657e+00 1.39433e+02 1.26880e-02]
 [1.99530e+00 7.21412e+01 2.75060e-02 6.25942e+00 1.34127e+02 4.80700e-03]
 [2.09463e+00 1.32219e+02 1.48670e-02 1.34743e-01 1.34841e+02 1.69450e-02]
 ...
 [2.24934e+00 1.01744e+02 2.86510e-02 2.08026e+00 1.10880e+02 4.39640e-02]
 [2.12298e+00 8.41852e+01 2.67900e-03 2.08071e+00 1.11557e+02 4.31150e-02]
 [2.51934e+00 1.07238e+02 7.10300e-03 7.02851e-01 4.17374e+01 1.60602e-01]]

Array after removing the fourth column:
[[3.90874e+00 6.15669e+01 5.26890e-02 2.01657e+00 1.26880e-02]
 [1.99530e+00 7.21412e+01 2.75060e-02 6.25942e+00 4.80700e-03]
 [2.09463e+00 1.32219e+02 1.48670e-02 1.34743e-01 1.69450e-02]
 ...
 [2.24934e+00 1.01744e+02 2.86510e-02 2.08026e+00 4.39640e-02]
 [2.12298e+00 8.41852e+01 2.67900e-03 2.08071e+00 4.31150e-02]
 [2.51934e+00 1.07238e+02 7.10300e-03 7.02851e-01 1.60602e-01]]


In [72]:
def positional_encoding(X,L):
    
    min = np.min(X)
    max = np.max(X)
    x = 2 * ((X-min)/(max-min)) - 1
    temp = []
    for l in range(L):
        value = 2 ** l
        sinx = np.sin(value * np.pi * x)
        cosx = np.cos(value * np.pi * x)
        temp.extend([sinx, cosx])
    temp = np.array(temp)
    temp = temp.T
    return temp

In [75]:
length2_pe = positional_encoding(X_length2, 3)


In [74]:
import numpy as np

# 创建两个示例二维数组
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8],
                   [9, 10]])

# 将数组2连接到数组1的右侧
result_array = np.concatenate((array1, array2), axis=1)

print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)
print("\nArray after concatenation:")
print(result_array)


Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[ 7  8]
 [ 9 10]]

Array after concatenation:
[[ 1  2  3  7  8]
 [ 4  5  6  9 10]]


In [52]:
X = [-1,0,1]
min = np.min(X)
max = np.max(X)
# print(min)

x = 2*((X-min)/(max-min))-1
temp = []
for l in range(3):
    value = 2 ** l
    # print(value)
    a = np.sin(value*np.pi*x)
    b = a+0.1
    temp.extend([a,b])
    
temp
print("temp",temp)
print("temp_T",np.array(temp).T)
    # sinx = np.sin(value * np.pi * x)
    # cosx = np.cos(value * np.pi * x)
    # temp.extend([sinx, cosx])

temp [array([-1.2246468e-16,  0.0000000e+00,  1.2246468e-16]), array([0.1, 0.1, 0.1]), array([ 2.4492936e-16,  0.0000000e+00, -2.4492936e-16]), array([0.1, 0.1, 0.1]), array([ 4.8985872e-16,  0.0000000e+00, -4.8985872e-16]), array([0.1, 0.1, 0.1])]
temp_T [[-1.2246468e-16  1.0000000e-01  2.4492936e-16  1.0000000e-01
   4.8985872e-16  1.0000000e-01]
 [ 0.0000000e+00  1.0000000e-01  0.0000000e+00  1.0000000e-01
   0.0000000e+00  1.0000000e-01]
 [ 1.2246468e-16  1.0000000e-01 -2.4492936e-16  1.0000000e-01
  -4.8985872e-16  1.0000000e-01]]


In [7]:
theta_x1 = np.cos(df[:, 2])
theta_x1 = theta_x1.reshape(-1, 1)
theta_y1 = np.sin(df[:, 2])
theta_y1 = theta_y1.reshape(-1, 1)
theta_x2 = np.cos(df[:, 5])
theta_x2 = theta_x2.reshape(-1, 1)
theta_y2 = np.sin(df[:, 5])
theta_y2 = theta_y2.reshape(-1, 1)

In [8]:
theta_x1

array([[0.99861226],
       [0.99962173],
       [0.99988949],
       ...,
       [0.99958959],
       [0.99999641],
       [0.99997477]])

In [9]:
# delete columns(OpeningAngle, OpeningAngle2)
columns_to_delete = [2, 5] 
df = np.delete(df, columns_to_delete, axis=1)

In [10]:
df

array([[3.90874e+00, 6.15669e+01, 2.01657e+00, 1.39433e+02, 0.00000e+00,
        4.07216e+00],
       [1.99530e+00, 7.21412e+01, 6.25942e+00, 1.34127e+02, 0.00000e+00,
        4.18268e+00],
       [2.09463e+00, 1.32219e+02, 1.34743e-01, 1.34841e+02, 0.00000e+00,
        3.72230e+00],
       ...,
       [2.24934e+00, 1.01744e+02, 2.08026e+00, 1.10880e+02, 3.10000e+01,
        4.01570e+00],
       [2.12298e+00, 8.41852e+01, 2.08071e+00, 1.11557e+02, 3.10000e+01,
        4.15416e+00],
       [2.51934e+00, 1.07238e+02, 7.02851e-01, 4.17374e+01, 3.10000e+01,
        4.63660e+00]])

In [11]:
df = np.concatenate((df, theta_x1), axis=1)
df = np.concatenate((df, theta_y1), axis=1)
df = np.concatenate((df, theta_x2), axis=1)
df = np.concatenate((df, theta_y2), axis=1)

In [12]:
df

array([[3.90874000e+00, 6.15669000e+01, 2.01657000e+00, ...,
        5.26646248e-02, 9.99919508e-01, 1.26876596e-02],
       [1.99530000e+00, 7.21412000e+01, 6.25942000e+00, ...,
        2.75025317e-02, 9.99988446e-01, 4.80698149e-03],
       [2.09463000e+00, 1.32219000e+02, 1.34743000e-01, ...,
        1.48664523e-02, 9.99856437e-01, 1.69441891e-02],
       ...,
       [2.24934000e+00, 1.01744000e+02, 2.08026000e+00, ...,
        2.86470803e-02, 9.99033739e-01, 4.39498389e-02],
       [2.12298000e+00, 8.41852000e+01, 2.08071000e+00, ...,
        2.67899680e-03, 9.99070692e-01, 4.31016435e-02],
       [2.51934000e+00, 1.07238000e+02, 7.02851000e-01, ...,
        7.10294027e-03, 9.87131195e-01, 1.59912489e-01]])

In [13]:
y = df[:, 5]
y

array([4.07216, 4.18268, 3.7223 , ..., 4.0157 , 4.15416, 4.6366 ])

In [14]:
X = df[:, np.arange(df.shape[1]) != 5]
X

array([[3.90874000e+00, 6.15669000e+01, 2.01657000e+00, ...,
        5.26646248e-02, 9.99919508e-01, 1.26876596e-02],
       [1.99530000e+00, 7.21412000e+01, 6.25942000e+00, ...,
        2.75025317e-02, 9.99988446e-01, 4.80698149e-03],
       [2.09463000e+00, 1.32219000e+02, 1.34743000e-01, ...,
        1.48664523e-02, 9.99856437e-01, 1.69441891e-02],
       ...,
       [2.24934000e+00, 1.01744000e+02, 2.08026000e+00, ...,
        2.86470803e-02, 9.99033739e-01, 4.39498389e-02],
       [2.12298000e+00, 8.41852000e+01, 2.08071000e+00, ...,
        2.67899680e-03, 9.99070692e-01, 4.31016435e-02],
       [2.51934000e+00, 1.07238000e+02, 7.02851000e-01, ...,
        7.10294027e-03, 9.87131195e-01, 1.59912489e-01]])

In [15]:
X.shape

(1600, 9)

In [18]:
np.set_printoptions(threshold=np.inf)
print(X[:1])

[[3.90874000e+00 6.15669000e+01 2.01657000e+00 1.39433000e+02
  0.00000000e+00 9.98612256e-01 5.26646248e-02 9.99919508e-01
  1.26876596e-02]]
